### ISSUE TITLE
Div Overflowing bug

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#945] opened 2019-03-26 13:44 UTC
### The select module div overflows over the "Add Step" button.

Firefox 
![image](https://user-images.githubusercontent.com/26546120/55001638-10dfd180-4ffb-11e9-8439-4b72f4fab54c.png)

I ll solve this, but right now I don't have time , I ll do this after 29th March.

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Divy123** [comment] 2019-03-26 18:40
@aashna27 this issue is already being discussed in 
https://github.com/publiclab/image-sequencer/pull/909.

**Comment by HarshKhandeparkar** [comment] 2019-03-26 18:42
#909 doesn't fix it. Doesn't work

**Comment by Divy123** [comment] 2019-03-26 19:01
Yup but I think this being a first timer issue can be made avaialable for first timers.

**Comment by HarshKhandeparkar** [comment] 2019-03-26 19:08
So what should be done?

**Comment by HarshKhandeparkar** [comment] 2019-03-26 19:08
Duplicate of #894

**Comment by Divy123** [comment] 2019-03-26 19:13
I think this can be closed here.
Ask the person who has sent the PR there if he/she wants to continue.
If we don't get a reply within 2&3 days we can reassign it.

**Closed** 2019-03-26 19:15 UTC

**Comment by aashna27** [comment] 2019-03-27 07:55
Okay , cool .. if this is being kept as an fto people can go ahead and if they aren't able to solve it , I would like to go forward with it ! @Divy123 @HarshKhandeparkar
