### ISSUE TITLE
Fix alignment of image sequencer description

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#390] opened 2018-10-05 20:22 UTC
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem 
Fixing the alignment of image sequencer description found on the home page.

### 📋 Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files $index.html and $demo.css in the `$examples` repository (press the little pen Icon) and edit as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is an explanation to go about the Solution :

 1. Go to line 43 of index.html:
```diff
      <p>
```
2. And modify it as-
```diff
       <p class="description-container">
```
3.Then go to demo.css in $examples repository and add the following lines at the end of the stylesheet-

```addition
p.description-container {
    width: 65%;
    margin: 15px auto;
}
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Paarmita** [comment] 2018-10-05 20:52
@aashna27 Can u please also provide the misplaced alignment of image sequencer description, in order to understand the problem better?
Thanks!

**Comment by aashna27** [comment] 2018-10-05 21:31
Yeah sure @Paarmita 
The previous alignment of the description is as follows:
![image](https://user-images.githubusercontent.com/26546120/46560726-738cc600-c912-11e8-8060-b56854c108e0.png)

The modified look will be :
![image](https://user-images.githubusercontent.com/26546120/46561097-c61ab200-c913-11e8-8689-0de06616a4dd.png)

**Comment by gowrimanoharir** [comment] 2018-10-05 23:32
Hi, can I work on this?

**Comment by tech4GT** [comment] 2018-10-05 23:34
Hello @aashna27 the description is supposed to take up that width, it's not a bug. Closing this one now. Thanks for your help!!

**Closed by tech4GT** 2018-10-05 23:34 UTC
Labels: first-timers-only, help wanted, question
