### ISSUE TITLE
remove unwanted slider

### ISSUE THREAD

**Issue by avsingh999** [publiclab/image-sequencer#850] opened 2019-03-12 08:07 UTC
### Please describe the problem (or idea)
I think there is an unwanted slider (left-right) so I think should remove that slider.
![pu4](https://user-images.githubusercontent.com/25536022/54184161-f4587b00-44cb-11e9-9ad6-4c65b4754915.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment] 2019-03-12 08:26
Does this only occur on small screens? Or also on PC sized screens?

**Comment by avsingh999** [comment] 2019-03-12 08:47
@HarshKhandeparkar  Yes there is also slider but In  Mobile and not looking good for mobile. In the sense not responsive for mobile we Can in the gif.
thanks : )
![pub3](https://user-images.githubusercontent.com/25536022/54186460-78613180-44d1-11e9-9757-06386c0ab749.gif)

**Comment by HarshKhandeparkar** [comment] 2019-03-12 10:41
Any ideas which element is causing this?

**Comment by Harshithpabbati** [comment] 2019-03-12 11:10
@avsingh999 I am not able to reproduce the issue.

**Comment by HarshKhandeparkar** [comment] 2019-03-12 11:12
@avsingh999 you seem to be using an old version of IS. Try rebasing or clearing the cache. If you are using sequencer.publiclab.org then it is ~20days old.

**Comment by Harshithpabbati** [comment] 2019-03-12 11:14
@HarshKhandeparkar even the sequencer.publiclab.org looks good.

**Comment by avsingh999** [comment] 2019-03-12 14:24
@HarshKhandeparkar @Harshithpabbati I getting here sequencer.publiclab.org.Let me see on local machine
thanks : )

**Comment by avsingh999** [comment] 2019-03-12 14:26
@HarshKhandeparkar @Harshithpabbati I getting here sequencer.publiclab.org.Let me see on local machine
thanks : )

**Comment by avsingh999** [comment] 2019-03-12 14:35
@Harshithpabbati @HarshKhandeparkar But I think need to improve for mobile UI.

**Comment by Harshithpabbati** [comment] 2019-03-12 14:42
@jywarren it looks good even in the mobile ui isn't it??

**Comment by avsingh999** [comment] 2019-03-12 15:29
@Harshithpabbati I think the problem in save sequence and view Gif button
thanks : )

**Comment by Harshithpabbati** [comment] 2019-03-12 15:58
![phoneversion](https://user-images.githubusercontent.com/43822585/54215204-8df44c80-450d-11e9-80a6-e36a31bf011e.jpg)
It look's cool in my phone @avsingh999 
Let's ask the other reviewers @publiclab/is-reviewers is it the thing???

**Comment by HarshKhandeparkar** [comment] 2019-03-12 16:09
It works fine on my phone as well. Maybe it is resolution dependent? Try it in ur browser and try resizing it and try to find out the threshold. Thanks.

**Comment by Harshithpabbati** [comment] 2019-03-12 16:18
Yeah we need the slider for the smaller screens. Or else the view gif will be vanished.

**Comment by avsingh999** [comment] 2019-03-16 06:43
@Harshithpabbati @HarshKhandeparkar yes also working fine in my phone,and I was looking in chrome mobile view so I got this.
thanks : )

**Comment by HarshKhandeparkar** [comment] 2019-03-16 06:53
Did you try it on the latest version?

**Comment by HarshKhandeparkar** [comment] 2019-03-16 07:01
Oh cool! #821 fixes this. I will link to the issue in the pr.

**Comment by Harshithpabbati** [comment] 2019-03-16 07:55
I guess we can close this.

**Comment by HarshKhandeparkar** [comment] 2019-03-16 07:56
This will be closed when that pr is merged

**Comment by Harshithpabbati** [comment] 2019-03-16 07:57
There is already an issue right?? So we can close it.

**Comment by HarshKhandeparkar** [comment] 2019-03-16 07:58
Maybe the pr doesn't fix this? No screenshots are provided there. So lets wait

**Comment by Harshithpabbati** [comment] 2019-03-16 07:59
Oh ok

**Comment by jywarren** [comment] 2019-04-08 21:07
Oh, thanks a million, everyone, for helping solve this!!!

**Comment by HarshKhandeparkar** [comment] 2020-01-17 19:12
Fixed Elsewhere, I guess.

**Closed by HarshKhandeparkar** 2020-01-17 19:12 UTC
Labels: enhancement, has-pull-request
