### ISSUE TITLE
Add blur radius

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#944] opened 2019-03-25 21:14 UTC
It'd be great to be able to set a "radius" for the blur, to make it much blurrier!

https://sequencer.publiclab.org/examples/#steps=threshold{input:100},blur{blur:20}

Love help with this!

**Comment by HarshKhandeparkar** [comment] 2020-01-17 19:23
Duplicate of https://github.com/publiclab/image-sequencer/issues/1223

**Closed by HarshKhandeparkar** 2020-01-17 19:23 UTC
Labels: enhancement, help wanted
