### ISSUE TITLE
Error on dropDown modules section

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1005] opened 2019-04-11 16:18 UTC
### The dropdown menu shows error when a its clicked to select a Module.
![image](https://user-images.githubusercontent.com/26546120/55973650-a8a01980-5ca3-11e9-8777-73277f0eacf5.png)

![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/26546120/55973713-cbcac900-5ca3-11e9-853a-835fa36a226e.gif)

### Please show us where to look

https://beta.sequencer.publiclab.org

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by bhavayAnand9** [comment] 2019-04-11 18:35
I'm not getting this error. Can you please check if your branch is updated?
![Apr-12-2019 00-00-33](https://user-images.githubusercontent.com/34943807/55982234-22d99980-5cb6-11e9-9ac1-3c213a84882f.gif)

**Comment by Harshithpabbati** [comment] 2019-04-18 12:13
I can't reproduce the issue.

**Comment by HarshKhandeparkar** [comment] 2019-04-18 12:16
This is probably outdated. Even I couldn't reproduce the error. I am closing this **for now**. Let's see if we get the error again. @aashna27

**Closed by HarshKhandeparkar** 2019-04-18 12:16 UTC
Labels: bug, help-wanted, more-details-please
