### ISSUE TITLE
Bugs in Blur module and modules which are using blur module

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1292] opened 2019-11-06 13:35 UTC
there is a bug in blur module and modules that are using it(edge-detect).This works fine for me on desktop site but on mobile device it as shown
![Screenshot_20191105-151912_Chrome (1)](https://user-images.githubusercontent.com/45951376/68302469-21dfdd80-00c8-11ea-8f2e-0ac85e877bfa.jpg)

**Comment by keshav234156** [comment] 2019-11-06 13:35
cc @jywarren  @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment] 2019-12-11 16:19
I'll look into this.

**Comment by blurry-x-face** [comment] 2019-12-18 08:22
I found this issue with every module i tried, this is not just limited to blur module
![80551331_975376742848830_6256143483266924544_n](https://user-images.githubusercontent.com/42492389/71068813-826d3a80-219d-11ea-94cd-d3bfadd7cbf7.png)
@HarshKhandeparkar @keshav234156

**Comment by blurry-x-face** [comment] 2019-12-18 11:49
I tried older implementation of blur module, it works fine. Maybe the gpu acceleration has something to do with the issue.
![79540663_436892703923868_7533146000349724672_n](https://user-images.githubusercontent.com/42492389/71083934-22d15800-21ba-11ea-8977-834f2714abfa.png)

cc: @Divy123  @HarshKhandeparkar @keshav234156

**Comment by HarshKhandeparkar** [comment] 2019-12-18 13:04
Yes GPU acceleration is the issue but the issues are fixed in the latest
version. The issue is that we are having troubles in installing the latest
version. Remember that PR?

**Comment by blurry-x-face** [comment] 2019-12-18 13:20
Who made that PR, Do you remember it?

**Comment by HarshKhandeparkar** [comment] 2019-12-18 13:22
It's a new pr.

**Comment by blurry-x-face** [comment] 2019-12-18 13:26
Also, it uses same kernel size for different Sigma values, Shouldn't it use different kernel size according to the value of sigma?

**Comment by HarshKhandeparkar** [comment] 2019-12-18 13:27
Nope. Sigma decides the values *of* the kernel not the kernel size.

**Closed** 2019-12-21 16:59 UTC
