### ISSUE TITLE
While croping the image, when we increase the width image repeats itself.

### ISSUE THREAD

**Issue by amreshk005** [publiclab/image-sequencer#1276] opened 2019-10-16 03:24 UTC
<h3>While cropping the image, when we increase the width more than it's original width image gets repeated</h3>

> What did you expect to see that you didn't?

<p>The image shouldn't get repeat after the increment of width.</p>

![Screen Shot 2019-10-16 at 8 51 25 AM](https://user-images.githubusercontent.com/35935083/66885553-42010d00-eff2-11e9-9771-259e8f6c0f89.jpg)

**Comment by amreshk005** [comment] 2019-10-16 03:33
@jywarren Please review this issue, is this a valid?

if it is valid I would like work on this issue

**Comment by keshav234156** [comment] 2019-10-16 10:46
@amreshk005 Thanks for opening the issue.I also noticed this bug earlier.I think expected behaviour should be to add whitespace as it does with the height.It must be an easy fix as behaviour of height is correct which just need to make some changes with height as well.Go ahead!!

**Comment by keshav234156** [comment] 2019-10-16 10:54
@HarshKhandeparkar what do you think?

**Comment by vaibhavmatta** [comment] 2019-10-16 12:49
@amreshk005 , @keshav234156 
I think Crop means to cut out unwanted part from Image either Horizontally (along Width) or Vertically (along height). Thus, the user must not write values greater than Orignal width and height of the Image. There should be error whenever User fills greater value in Width or Height.
Thanks 😊

**Comment by vaibhavmatta** [comment] 2019-10-16 12:52
@keshav234156 , @amreshk005 
Rather we should ask user to enter PERCENTAGE of WIDTH/HEIGHT Crop. It will look much professional and will be much easier for user to crop by adding % value as every user is not familiar with the dimensions of the Image he is working on.

**Comment by HarshKhandeparkar** [comment] 2019-10-20 18:21
I think Vaibhav is right here. That would be much better but we will still have to add error handling because user can enter >100%.

@amreshk005 you can add that as a possible fix to this issue body itself.

Amresh can still work on the issue.

**Comment by vaibhavmatta** [comment] 2019-10-21 14:05
@amreshk005 Please confirm it once if you are working on it? 
if YES, then please keep giving the updates regarding the issue so that I and @HarshKhandeparkar can plan for further actions on this module. Thanks 😊

**Comment by amreshk005** [comment] 2019-10-22 03:00
@vaibhavmatta @HarshKhandeparkar I would like to work on this.

**Comment by vaibhavmatta** [comment] 2019-10-22 04:36
@amreshk005 Plz do it. Tag me up wherever you feel stuck. 
Happy Coding!

**Comment by vaibhavmatta** [comment] 2019-10-27 20:17
@amreshk005 any updates?
Are you still working on it?

**Comment by jywarren** [comment] 2019-10-28 14:29
Hi all, just noting that I think there are moments when "overcropping" is
useful, where you want to add white space around an image. So perhaps we
could solve this by adding a conditional for whether a pixel is outside the
original bounds, and adding either white or fully transparent pixels?

**Comment by vaibhavmatta** [comment] 2019-10-28 17:27
@jywarren You are right but this feature doesn’t fits to the exact meaning of CROP . We can make this feature an another module by the name lets say, add base, add bg etc . 
Thanks

**Comment by jywarren** [comment] 2019-11-27 20:05
Actually i think there are some current use cases that do "overcropping" and we shouldn't prevent it even if we later clarify things better. Let's just be sure this can still be possible! Thanks!

**Comment by keshav234156** [comment] 2020-01-12 18:34
we can close this issue as overcropping is helpful also!!!

**Closed** 2020-01-12 18:33 UTC
Labels: gci-candidate
